/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color Tokens — SIA INSTIPER
        'surface-bright': '#f9f9fc',
        'tertiary-fixed': '#cee9d3',
        'secondary-container': '#92f7c3',
        'secondary-fixed-dim': '#75daa8',
        'error-container': '#ffdad6',
        'on-primary-container': '#86af99',
        'on-tertiary-fixed-variant': '#354c3b',
        'inverse-primary': '#a5d0b9',
        'on-surface-variant': '#414844',
        tertiary: '#152b1c',
        'surface-container': '#eeeef0',
        'on-surface': '#1a1c1e',
        'on-secondary-fixed': '#002113',
        'on-tertiary-container': '#93ad98',
        'secondary-fixed': '#92f7c3',
        'inverse-on-surface': '#f0f0f3',
        'primary-fixed': '#c1ecd4',
        'surface-container-high': '#e8e8ea',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#005235',
        'surface-dim': '#dadadc',
        'primary-fixed-dim': '#a5d0b9',
        'on-tertiary-fixed': '#092012',
        'surface-variant': '#e2e2e5',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1b4332',
        primary: '#012d1d',
        'surface-container-highest': '#e2e2e5',
        'on-secondary': '#ffffff',
        'on-background': '#1a1c1e',
        'on-secondary-container': '#00734d',
        'surface-tint': '#3f6653',
        'inverse-surface': '#2f3133',
        'outline-variant': '#c1c8c2',
        outline: '#717973',
        surface: '#f9f9fc',
        'surface-container-low': '#f3f3f6',
        'tertiary-container': '#2a4131',
        'tertiary-fixed-dim': '#b3cdb7',
        'on-primary-fixed-variant': '#274e3d',
        'on-primary-fixed': '#002114',
        background: '#f9f9fc',
        secondary: '#006c48',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        xl: '64px',
        lg: '40px',
        base: '8px',
        md: '24px',
        xs: '4px',
        margin: '32px',
        gutter: '24px',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        display: ['Manrope'],
        'body-sm': ['Manrope'],
        h1: ['Manrope'],
        'body-lg': ['Manrope'],
        h2: ['Manrope'],
        'label-sm': ['Manrope'],
        'body-md': ['Manrope'],
        h3: ['Manrope'],
        'label-md': ['Manrope'],
      },
      fontSize: {
        display: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        'level-1': '0px 4px 20px rgba(0, 0, 0, 0.04)',
        'level-2': '0px 10px 32px rgba(27, 67, 50, 0.08)',
      },
    },
  },
}
