name: Deploy SIA INSTIPER ke GitHub Pages

on:
  push:
    branches:
      - main

# Menambahkan permissions secara global atau pastikan job deploy memilikinya
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # Menambahkan cache agar instalasi berikutnya lebih cepat

      - run: npm install

      - run: npx nuxt build --preset github_pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pastikan path ini sesuai dengan output Nuxt 3
          path: ./.output/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
